// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udgmqrppwiwrfjwikbtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZ21xcnBwd2l3cmZqd2lrYnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTAzNTgsImV4cCI6MjA2NDE2NjM1OH0.yvS720EAoTv5Lbu429Hcw33t8yo3TbJuiPzujza1Sow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);